name: Build and Public Release

on:
  push:
    tags:
      - 'v*' # Se activa con tags como v1.3.5
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install pyinstaller pywebview
      
      # --- BUILD WINDOWS (Para Andrés) ---
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        # Todo en una sola línea para evitar errores de sintaxis en PowerShell
        run: pyinstaller --noconfirm --windowed --onefile --name "MATI" --icon="frontend/assets/icon.ico" --add-data "frontend;frontend" --add-data "core;core" main.py
        
      - name: Upload Windows to Release
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          repository: lexrammart/MATI-Releases 
          token: ${{ secrets.RELEASE_TOKEN }}
          target_commitish: main
          tag_name: ${{ github.ref_name }}
          files: dist/MATI.exe
          
      - name: Build Mac
        if: matrix.os == 'macos-latest'
        run: |
          # Agregamos --onefile para que sea un solo ejecutable sólido
          pyinstaller --noconfirm --windowed --onefile --name "MATI" \
          --icon="frontend/assets/icon.icns" \
          --target-arch universal2 \
          --add-data "frontend:frontend" \
          --add-data "core:core" \
          main.py

      - name: Zip Mac App
        if: matrix.os == 'macos-latest'
        run: cd dist && zip -r MATI-macOS.zip MATI.app

      - name: Upload Mac to Release
        if: matrix.os == 'macos-latest'
        uses: softprops/action-gh-release@v2
        with:
          repository: lexrammart/MATI-Releases 
          token: ${{ secrets.RELEASE_TOKEN }}
          target_commitish: main
          tag_name: ${{ github.ref_name }}
          files: dist/MATI-macOS.zip
